name: 'Build'

on:
  [ push ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: git fetch origin --tags
        shell: bash
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build -DGITHUB_USERNAME=${{ github.actor }} -DGITHUB_TOKEN=${{ secrets.REP_TOKEN }} -x check --max-workers 1
      - name: Archive build results
        run: tar -I zstd -cf build.tar.zst build/libs
      - name: List build directory contents
        run: ls -R build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build.tar.zst
          if-no-files-found: error
          retention-days: 3
